### PR TITLE
Fixing the bug with missing metrics if there are more than 1 combination of dimension values

### PR DESCRIPTION
**Pull request by vzhabiuks**

### CODE REVIEW

**Comment by vzhabiuks** [comment]
CC @cep21

**Comment by vzhabiuks** [comment]
Added more metrics. Fixed the bug with missing metrics for some dimensions

**Comment by cep21** [comment]
Why change stats from a map?

**Comment by vzhabiuks** [comment]
metric name was the key in that dictionary,  the value was a tuple of
metric's value and the set of dimensions. The problem is that for a
particular metric name there might be mupltiple values corresponding a
combination of dimension values
I had to change it to a list of tuples (metric_name, metric_value,
dimensions_dict)

**Pull request merged**
